FROM node:12-alpine
WORKDIR /app

ARG CI_COMMIT_TAG
ARG CI_COMMIT_REF_SLUG
ARG BUILD_DATE
ARG BUILD_ENV

ENV CI_COMMIT_TAG=${CI_COMMIT_TAG}
ENV NUXT_ENV_BUILD_TAG=${CI_COMMIT_TAG}
ENV NUXT_ENV_BUILD_BRANCH=${CI_COMMIT_REF_SLUG}
ENV NUXT_ENV_BUILD_DATE=${BUILD_DATE}
ENV BUILD_ENV=${BUILD_ENV}

COPY ./package*.json ./
RUN npm i

COPY ./ ./
RUN npm run build
CMD [ "npm", "start" ]
